/**
 * Monitoring Module Types
 * Types for Checkers, Checks, Reports, and related entities
 */

/**
 * CheckerService
 * Enum for checker service types (integer enum from backend)
 * Since exact values are not specified in documentation, using number type
 * that can be refined when API integration provides actual enum values
 */
export type CheckerService = number

/**
 * ConfigField
 * Field definition for checker configuration (from config_fields)
 */
export interface ConfigField {
  type: 'integer' | 'boolean' | 'select' | 'string'
  label: string
  default?: any
  min?: number
  max?: number
  options?: Array<{ value: any; label: string }>
  cron?: string
  timeout?: number
  verify_ssl?: boolean
}

/**
 * ResultField
 * Field definition for checker result (from result_fields)
 */
export interface ResultField {
  label: string
}

/**
 * JobDTO
 * Job execution history from Horizon/Redis
 */
export interface JobDTO {
  id: string
  status: string
  created_at: string
  finished_at?: string
  // Additional fields based on actual API response
  [key: string]: any
}

/**
 * ReportField
 * Field in report with formatted value and optional color indicator
 */
export interface ReportField {
  label: string
  value: any
  color?: string // Optional color for status indication
}

/**
 * Checker
 * Checker model - defines a type of check that can be performed
 */
export interface Checker {
  id: number
  title: string
  service: CheckerService
  config: Record<string, any> | null
  is_active: boolean
  created_at: string
  updated_at: string
  // Appended fields (only on show endpoint)
  config_fields?: Record<string, ConfigField>
  result_fields?: Record<string, ResultField>
}

/**
 * Check
 * A check instance that runs a checker against specific pages
 */
export interface Check {
  id: number
  client_id: number
  title: string
  checker_id: number
  page_ids: number[]
  config: Record<string, any> | null
  is_active: boolean
  created_at: string
  updated_at: string
  // Appended fields (on index/show endpoints)
  checker?: Checker
  // Appended on run-history endpoints
  runHistory?: JobDTO[]
}

/**
 * Report
 * Report generated by a checker run
 */
export interface Report {
  id: number
  check_id: number
  page_id: number | null
  result: Record<string, any>
  created_at: string
  updated_at: string
  // Relations (loaded on index/show)
  check?: {
    id: number
    title: string
    checker?: {
      id: number
      title: string
      service: CheckerService
    }
  }
  page?: {
    id: number
    title: string
    slug: string
    website_id: number
    website?: {
      id: number
      host: string
    }
  }
  // Appended fields (on index/show endpoints)
  report_fields?: Record<string, ReportField>
}

/**
 * DTO Types for API requests
 */

export interface CheckerCreateDTO {
  title: string
  service: CheckerService
  config?: Record<string, any>
  is_active?: boolean
}

export interface CheckerUpdateDTO {
  title?: string
  service?: CheckerService
  config?: Record<string, any>
  is_active?: boolean
}

export interface CheckCreateDTO {
  client_id: number
  title: string
  checker_id: number
  page_ids?: number[]
  config?: Record<string, any>
  is_active?: boolean
}

export interface CheckUpdateDTO {
  client_id?: number
  title?: string
  checker_id?: number
  page_ids?: number[]
  config?: Record<string, any>
  is_active?: boolean
}

